### ISSUE TITLE
Problems with Hebrew characters

### ISSUE THREAD

**Issue by acka47** [skohub-io/skohub-vocabs#256]
I got this reported by @heiss who uses SkoHub Vocabs for a small group project:

> ich möchte Sie hiermit informieren, dass es ein Problem mit Skohub-vocab 
> gibt, wenn man hebräische Zeichen nutzt. Dann erscheint die Nachricht: 
> "No definition in language "undefined" provided."
> 
> https://heiss.github.io/skohub-docker-vocabs-correspondence/ulb.uni-muenster.de/vocab/skos/bible.he.html#zohar  

GitHub repo: https://github.com/Heiss/skohub-docker-vocabs-correspondence

**Comment by acka47** [comment]
I have also built in on the test server, where the same problem occurs:

https://test.skohub.io/acka47/skohub-docker-vocabs-correspondence/heads/main/ulb.uni-muenster.de/vocab/skos/bible.he.html

**Comment by sroertgen** [comment]
Note to myself: JSON Link in the hebrew repo seems not to be working

**Comment by sroertgen** [comment]
I forked the repo and rebuild the vocab: https://sroertgen.github.io/skohub-docker-vocabs-correspondence/ulb.uni-muenster.de/vocab/skos/bible.he.html#kabbalah

Everything seems to be there as expected. I suspect the issue arose from using an old docker image, which was not yet updated with the current state of master (now main).

A simple rebuild should fix the issue

JSON Link is also working

**Comment by sroertgen** [comment]
ping @Heiss

I will close this now, feel free to reopen if the issue persists

**Comment by sroertgen** [comment]
btw a rebuild is triggered with "Actions" > "Build /public and deploy to gh-pages with docker container " and click "Run Workflow"

**Comment by Heiss** [comment]
https://heiss.github.io/skohub-docker-vocabs-correspondence/ulb.uni-muenster.de/vocab/skos/bible.he.html#letters

Sadly, it`s still broken on my side. I used the latest tag in workflow: https://github.com/Heiss/skohub-docker-vocabs-correspondence/blob/main/.github/workflows/main.yml

The workflow checks for changed files, so it does not work with your suggested way to trigger it.

**Comment by Heiss** [comment]
Yep, now it`s fixed for me, too. Think github cache was a thing. ;) I used another browser before to verify, that there was no caching problem on my side. But i forgot, that github have one.

@acka47 yep, there are missing labels on purpose. We wrote about it in the project report.

Thank you all for your help.
